// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Channel struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

type Membership struct {
	ID        int64
	UserID    int64
	ChannelID int64
	CreatedAt time.Time
}

type Session struct {
	ID           uuid.UUID
	Email        string
	UserAgent    string
	ClientIp     string
	RefreshToken string
	ExpiresAt    time.Time
	IsBlocked    bool
	IsLoggedOut  bool
	CreatedAt    time.Time
}

type User struct {
	ID             int64
	Username       string
	Email          string
	HashedPassword string
	Phone          *string
	CreatedAt      time.Time
}
